name: Build and Release (Windows)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from tag
        if: startsWith(github.ref, 'refs/tags/')
        shell: pwsh
        run: |
          $ver = $env:GITHUB_REF -replace '^refs/tags/v',''
          echo "VERSION=$ver" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Set default version for manual runs
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        shell: pwsh
        run: |
          if (-not $env:VERSION) { echo "VERSION=0.0.0" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8 }

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller

      - name: Build EXE
        shell: pwsh
        run: tools/build/build_exe.ps1

      - name: Create portable ZIP
        shell: pwsh
        run: |
          Set-Location dist
          $zipName = "MCCraftingCalculator-Portable-v$env:VERSION.zip"
          if (Test-Path $zipName) { Remove-Item -Force $zipName }
          Compress-Archive -Path 'MCCraftingCalculator/*' -DestinationPath $zipName

      - name: Install Inno Setup
        shell: pwsh
        run: choco install innosetup --no-progress -y

      - name: Build Installer (Inno Setup)
        shell: pwsh
        run: |
          $iscc = 'C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe'
          if (-not (Test-Path $iscc)) { $iscc = 'C:\\Program Files\\Inno Setup 6\\ISCC.exe' }
          & $iscc /DMyAppVersion=$env:VERSION /DMyAppPublisher="Benedikt Wiesner" tools\build\installer.iss
          $src = 'dist/installer/MCCraftingCalculator-Setup.exe'
          $dst = "dist/installer/MCCraftingCalculator-Setup-v$env:VERSION.exe"
          Copy-Item $src $dst -Force

      - name: Upload Release (tagged)
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/MCCraftingCalculator/MCCraftingCalculator.exe
            dist/MCCraftingCalculator-Portable-v*.zip
            dist/installer/MCCraftingCalculator-Setup-v*.exe
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts (for non-tag runs)
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            dist/MCCraftingCalculator/**
            dist/MCCraftingCalculator-Portable-v*.zip
            dist/installer/MCCraftingCalculator-Setup-v*.exe
