name: Build and Release (Windows)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller

      - name: Build EXE
        shell: pwsh
        run: tools/build/build_exe.ps1

      - name: Create portable ZIP
        shell: pwsh
        run: |
          Set-Location dist
          Compress-Archive -Path 'MinecraftFarmCalc/*' -DestinationPath 'MinecraftFarmCalc-Portable.zip'

      - name: Install Inno Setup
        shell: pwsh
        run: choco install innosetup --no-progress -y

      - name: Build Installer (Inno Setup)
        shell: pwsh
        run: |
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' tools\build\installer.iss

      - name: Upload Release (tagged)
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/MinecraftFarmCalc/MinecraftFarmCalc.exe
            dist/MinecraftFarmCalc-Portable.zip
            dist/installer/MinecraftFarmCalculator-Setup.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts (for non-tag runs)
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            dist/MinecraftFarmCalc/**
            dist/MinecraftFarmCalc-Portable.zip
            dist/installer/MinecraftFarmCalculator-Setup.exe
